# General site settings
title: Arlene Dcosta
description: A brief description of your site
theme: theme-name # The theme you're using for your site

# GitHub Pages settings
baseurl: /ArleneDcosta.github.io # The base URL for your site, often set to the repository name
url: https://arlenedcosta.github.io # The URL where your site will be hosted
permalink: /:title/ # The structure of permalinks for posts/pages

# Author information
author:
  name: Arlene
  email: your.email@example.com

# Build settings
markdown: kramdown # The Markdown parser to use
plugins:
  - jekyll-feed # Plugin for generating an Atom feed for your site
  - jekyll-seo-tag # Plugin for generating SEO metadata
